Results db
WildCodeSchool/2022_03_PHP_Lyon_P2_Green_Monkey pull request #34
Opened 2022-05-03 13:35 UTC by ghartemann

2022-05-03 13:52 UTC, aldaitzwild requested changes

2022-05-03 13:52 UTC, aldaitzwild commented on src/Controller/ResultController.php
> +    public function add(): void
Maybe not the most clever idea :
- You create function add() int the controller wich is not an action
- You instanciate two ResultManager for the same action (only one should be enough)

2022-05-03 15:27 UTC, ghartemann commented on src/Controller/ResultController.php
> +    public function add(): void
should be better now

2022-05-04 07:02 UTC, aldaitzwild approved these changes

2022-05-04 07:02 UTC, merged